INSERT IGNORE INTO songs (song_title, song_artist, song_year) VALUES ("Firework", "Katy Perry", 2010);
INSERT IGNORE INTO songs (song_title, song_artist, song_year) VALUES ("Your Man", "Josh Turner", 2005);
INSERT IGNORE INTO songs (song_title, song_artist, song_year) VALUES ("Dance The Night", "Dua Lipa", 2023);
INSERT IGNORE INTO songs (song_title, song_artist, song_year) VALUES ("Believe", "Cher", 1998);
INSERT IGNORE INTO songs (song_title, song_artist, song_year) VALUES ("Starships", "Nicki Minaj", 2012);
INSERT IGNORE INTO songs (song_title, song_artist, song_year) VALUES ("Espresso", "Sabrina Carpenter", 2024);
INSERT IGNORE INTO songs (song_title, song_artist, song_year) VALUES ("Shivers", "Ed Sheeran", 2021);
INSERT IGNORE INTO songs (song_title, song_artist, song_year) VALUES ("Let's Get Ridiculous", "Redfoo", 2013);
INSERT IGNORE INTO songs (song_title, song_artist, song_year) VALUES ("No Roots", "Alice Merton", 2016);
INSERT IGNORE INTO songs (song_title, song_artist, song_year) VALUES ("Nonsense", "Sabrina Carpenter", 2022);
INSERT IGNORE INTO genres (genre_name) VALUES ("Pop");
INSERT IGNORE INTO genres (genre_name) VALUES ("Country");
INSERT IGNORE INTO genres (genre_name) VALUES ("Disco");
INSERT IGNORE INTO genres (genre_name) VALUES ("EDM");
INSERT IGNORE INTO genre_membership VALUES ((SELECT song_id FROM songs WHERE song_title = "Firework"), (SELECT genre_id FROM genres WHERE genre_name = "Pop"));
INSERT IGNORE INTO genre_membership VALUES ((SELECT song_id FROM songs WHERE song_title = "Your Man"), (SELECT genre_id FROM genres WHERE genre_name = "Country"));
INSERT IGNORE INTO genre_membership VALUES ((SELECT song_id FROM songs WHERE song_title = "Dance The Night"), (SELECT genre_id FROM genres WHERE genre_name = "Pop"));
INSERT IGNORE INTO genre_membership VALUES ((SELECT song_id FROM songs WHERE song_title = "Dance The Night"), (SELECT genre_id FROM genres WHERE genre_name = "Disco"));
INSERT IGNORE INTO genre_membership VALUES ((SELECT song_id FROM songs WHERE song_title = "Believe"), (SELECT genre_id FROM genres WHERE genre_name = "Pop"));
INSERT IGNORE INTO genre_membership VALUES ((SELECT song_id FROM songs WHERE song_title = "Starships"), (SELECT genre_id FROM genres WHERE genre_name = "Pop"));
INSERT IGNORE INTO genre_membership VALUES ((SELECT song_id FROM songs WHERE song_title = "Espresso"), (SELECT genre_id FROM genres WHERE genre_name = "Pop"));
INSERT IGNORE INTO genre_membership VALUES ((SELECT song_id FROM songs WHERE song_title = "Espresso"), (SELECT genre_id FROM genres WHERE genre_name = "Disco"));
INSERT IGNORE INTO genre_membership VALUES ((SELECT song_id FROM songs WHERE song_title = "Shivers"), (SELECT genre_id FROM genres WHERE genre_name = "Pop"));
INSERT IGNORE INTO genre_membership VALUES ((SELECT song_id FROM songs WHERE song_title = "Let's Get Ridiculous"), (SELECT genre_id FROM genres WHERE genre_name = "EDM"));
INSERT IGNORE INTO genre_membership VALUES ((SELECT song_id FROM songs WHERE song_title = "No Roots"), (SELECT genre_id FROM genres WHERE genre_name = "Pop"));
INSERT IGNORE INTO genre_membership VALUES ((SELECT song_id FROM songs WHERE song_title = "Nonsense"), (SELECT genre_id FROM genres WHERE genre_name = "Pop"));